// deno_renderer: Headless Vulkan renderer with WebGPU API for TypeScript.
// Uses ash for Vulkan, wgpu-core + deno_webgpu for WebGPU, deno_core for V8.
// Creates an exportable VkImage and renders directly to it — zero copy.

use ash::vk;
use deno_core::{op2, JsRuntime, OpState, RuntimeOptions};
use prost::Message;
use std::ffi::CStr;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

pub mod gpu_share_proto {
    tonic::include_proto!("gpu_share");
}

pub mod wgpu_hal_bridge;

#[cfg(unix)]
type NativeHandle = i32; // fd
#[cfg(windows)]
type NativeHandle = *mut std::ffi::c_void; // HANDLE
#[cfg(unix)]
const INVALID_HANDLE: NativeHandle = -1;
#[cfg(windows)]
const INVALID_HANDLE: NativeHandle = std::ptr::null_mut();

// ---------------------------------------------------------------------------
// SharedSurfaceInfo — must match the C++ layout exactly (C ABI)
// ---------------------------------------------------------------------------
#[repr(C)]
#[derive(Clone, Copy, Debug)]
struct SharedSurfaceInfo {
    width: u32,
    height: u32,
    format: u32,          // VkFormat value
    memory_size: u64,     // VkDeviceSize
    memory_type_bits: u32,
}

// Input event types are now defined in gpu_share.proto and generated by prost.
// The old C ABI structs (InputEvent, ResizeData, etc.) are no longer needed
// since events are received as typed protobuf messages.

// ---------------------------------------------------------------------------
// GpuState — Vulkan resources shared between ops and render loop
// ---------------------------------------------------------------------------
#[allow(dead_code)]
struct GpuState {
    // Core Vulkan
    instance: ash::Instance,
    device: ash::Device,
    phys_device: vk::PhysicalDevice,
    graphics_queue: vk::Queue,
    graphics_queue_family: u32,
    command_pool: vk::CommandPool,

    // Double-buffer: scene renders to render_img, then copies to shared_img
    render_img: SharedImage,
    shared_img: SharedImage,
    image_format: vk::Format,

    // Raw protobuf-encoded InputEvent bytes for TypeScript to consume
    input_events: Vec<Vec<u8>>,

    // When true, WebGPU scenes handle rendering via wgpu-core
    webgpu_active: bool,
}

// ---------------------------------------------------------------------------
// SharedImage
// ---------------------------------------------------------------------------
struct SharedImage {
    image: vk::Image,
    memory: vk::DeviceMemory,
    handle: NativeHandle,
    width: u32,
    height: u32,
    memory_size: u64,
    memory_type_bits: u32,
}

unsafe fn find_memory_type(
    instance: &ash::Instance,
    phys_device: vk::PhysicalDevice,
    type_filter: u32,
    properties: vk::MemoryPropertyFlags,
) -> u32 {
    let mem_props = instance.get_physical_device_memory_properties(phys_device);
    for i in 0..mem_props.memory_type_count {
        if (type_filter & (1 << i)) != 0
            && mem_props.memory_types[i as usize]
                .property_flags
                .contains(properties)
        {
            return i;
        }
    }
    panic!("Failed to find suitable memory type");
}

unsafe fn create_shared_image(
    instance: &ash::Instance,
    device: &ash::Device,
    phys_device: vk::PhysicalDevice,
    width: u32,
    height: u32,
    format: vk::Format,
) -> SharedImage {
    #[cfg(unix)]
    let handle_type = vk::ExternalMemoryHandleTypeFlags::OPAQUE_FD;
    #[cfg(windows)]
    let handle_type = vk::ExternalMemoryHandleTypeFlags::OPAQUE_WIN32;

    let mut ext_mem_image_ci =
        vk::ExternalMemoryImageCreateInfo::default().handle_types(handle_type);

    let image_ci = vk::ImageCreateInfo::default()
        .push_next(&mut ext_mem_image_ci)
        .image_type(vk::ImageType::TYPE_2D)
        .format(format)
        .extent(vk::Extent3D {
            width,
            height,
            depth: 1,
        })
        .mip_levels(1)
        .array_layers(1)
        .samples(vk::SampleCountFlags::TYPE_1)
        .tiling(vk::ImageTiling::OPTIMAL)
        .usage(
            vk::ImageUsageFlags::COLOR_ATTACHMENT
                | vk::ImageUsageFlags::TRANSFER_DST
                | vk::ImageUsageFlags::TRANSFER_SRC
                | vk::ImageUsageFlags::SAMPLED,
        )
        .sharing_mode(vk::SharingMode::EXCLUSIVE)
        .initial_layout(vk::ImageLayout::UNDEFINED);

    let image = device
        .create_image(&image_ci, None)
        .expect("Failed to create image");

    let mem_reqs = device.get_image_memory_requirements(image);

    let mut export_alloc_info =
        vk::ExportMemoryAllocateInfo::default().handle_types(handle_type);

    let mem_type_index = find_memory_type(
        instance,
        phys_device,
        mem_reqs.memory_type_bits,
        vk::MemoryPropertyFlags::DEVICE_LOCAL,
    );

    let alloc_info = vk::MemoryAllocateInfo::default()
        .push_next(&mut export_alloc_info)
        .allocation_size(mem_reqs.size)
        .memory_type_index(mem_type_index);

    let memory = device
        .allocate_memory(&alloc_info, None)
        .expect("Failed to allocate memory");

    device
        .bind_image_memory(image, memory, 0)
        .expect("Failed to bind image memory");

    // Export handle
    #[cfg(unix)]
    let handle = {
        let ext = ash::khr::external_memory_fd::Device::new(instance, device);
        let get_fd_info = vk::MemoryGetFdInfoKHR::default()
            .memory(memory)
            .handle_type(vk::ExternalMemoryHandleTypeFlags::OPAQUE_FD);
        ext.get_memory_fd(&get_fd_info)
            .expect("Failed to export memory fd") as NativeHandle
    };

    #[cfg(windows)]
    let handle = {
        let ext = ash::khr::external_memory_win32::Device::new(instance, device);
        let get_handle_info = vk::MemoryGetWin32HandleInfoKHR::default()
            .memory(memory)
            .handle_type(vk::ExternalMemoryHandleTypeFlags::OPAQUE_WIN32);
        ext.get_memory_win32_handle(&get_handle_info)
            .expect("Failed to export memory handle") as NativeHandle
    };

    eprintln!(
        "[deno_renderer] Exported memory handle={:?} for {}x{} image (size={})",
        handle, width, height, mem_reqs.size
    );

    SharedImage {
        image,
        memory,
        handle,
        width,
        height,
        memory_size: mem_reqs.size,
        memory_type_bits: mem_reqs.memory_type_bits,
    }
}

unsafe fn destroy_shared_image(device: &ash::Device, img: &mut SharedImage) {
    if img.image != vk::Image::null() {
        device.destroy_image(img.image, None);
        img.image = vk::Image::null();
    }
    if img.memory != vk::DeviceMemory::null() {
        device.free_memory(img.memory, None);
        img.memory = vk::DeviceMemory::null();
    }
    #[cfg(unix)]
    if img.handle != INVALID_HANDLE {
        libc::close(img.handle as i32);
        img.handle = INVALID_HANDLE;
    }
    #[cfg(windows)]
    if img.handle != INVALID_HANDLE {
        unsafe {
            windows_sys::Win32::Foundation::CloseHandle(img.handle);
        }
        img.handle = INVALID_HANDLE;
    }
}


// ---------------------------------------------------------------------------
// Deno ops
// ---------------------------------------------------------------------------

/// Returns all pending input events as length-prefixed protobuf bytes.
/// Format: [u32le length][protobuf bytes][u32le length][protobuf bytes]...
/// TypeScript decodes each chunk using protobuf-es InputEvent.fromBinary().
#[op2]
#[buffer]
fn op_gpu_poll_events(state: &mut OpState) -> Vec<u8> {
    let gpu = state.borrow_mut::<Arc<Mutex<GpuState>>>();
    let mut gpu = gpu.lock().unwrap();
    let events = std::mem::take(&mut gpu.input_events);
    let mut buf = Vec::new();
    for ev_bytes in &events {
        let len = ev_bytes.len() as u32;
        buf.extend_from_slice(&len.to_le_bytes());
        buf.extend_from_slice(ev_bytes);
    }
    buf
}

#[op2(fast)]
fn op_gpu_set_webgpu_active(state: &mut OpState, active: bool) {
    let gpu = state.borrow_mut::<Arc<Mutex<GpuState>>>();
    let mut gpu = gpu.lock().unwrap();
    gpu.webgpu_active = active;
}

#[op2(fast)]
fn op_log(#[string] msg: &str) {
    eprintln!("[scene] {}", msg);
}

// ---------------------------------------------------------------------------
// gRPC transport (tonic client)
// ---------------------------------------------------------------------------
mod transport {
    use crate::gpu_share_proto;
    use crate::gpu_share_proto::renderer_bridge_client::RendererBridgeClient;
    use tokio::sync::mpsc;
    use tonic::transport::Channel;

    pub struct GrpcTransport {
        client: RendererBridgeClient<Channel>,
        event_rx: mpsc::UnboundedReceiver<gpu_share_proto::InputEvent>,
        #[allow(dead_code)]
        presenter_pid: u32,
    }

    impl GrpcTransport {
        pub async fn connect(
            port: &str,
            renderer_pid: u32,
            surface: &super::SharedSurfaceInfo,
            handle: super::NativeHandle,
            sem_handle: super::NativeHandle,
        ) -> Result<Self, String> {
            let addr = format!("http://127.0.0.1:{}", port);

            // Retry connection (presenter may still be starting)
            let channel = {
                let mut last_err = String::new();
                let mut ch = None;
                for _ in 0..20 {
                    match Channel::from_shared(addr.clone())
                        .map_err(|e| format!("invalid URI: {}", e))?
                        .connect()
                        .await
                    {
                        Ok(c) => {
                            ch = Some(c);
                            break;
                        }
                        Err(e) => {
                            last_err = format!("{}", e);
                            tokio::time::sleep(std::time::Duration::from_millis(300)).await;
                        }
                    }
                }
                ch.ok_or_else(|| format!("Failed to connect to {}: {}", addr, last_err))?
            };

            let mut client = RendererBridgeClient::new(channel);

            // Send Connect RPC
            let req = gpu_share_proto::ConnectRequest {
                renderer_pid,
                surface: Some(gpu_share_proto::SharedSurfaceInfo {
                    width: surface.width,
                    height: surface.height,
                    format: surface.format,
                    memory_size: surface.memory_size,
                    memory_type_bits: surface.memory_type_bits,
                }),
                #[cfg(unix)]
                memory_handle: handle as u64,
                #[cfg(windows)]
                memory_handle: handle as u64,
                semaphore_handle: sem_handle as u64,
            };

            let resp = client
                .register_surface(req)
                .await
                .map_err(|e| format!("RegisterSurface RPC failed: {}", e))?;
            let presenter_pid = resp.into_inner().presenter_pid;
            eprintln!(
                "[transport] Connected to presenter (pid={})",
                presenter_pid
            );

            // Start StreamInput in a background task
            let (tx, rx) = mpsc::unbounded_channel();
            let mut stream_client = client.clone();
            tokio::spawn(async move {
                let req = gpu_share_proto::StreamInputRequest {};
                match stream_client.stream_input(req).await {
                    Ok(response) => {
                        let mut stream = response.into_inner();
                        while let Ok(Some(ev)) = stream.message().await {
                            if tx.send(ev).is_err() {
                                break;
                            }
                        }
                    }
                    Err(e) => {
                        eprintln!("[transport] StreamInput error: {}", e);
                    }
                }
                eprintln!("[transport] StreamInput ended");
            });

            Ok(GrpcTransport {
                client,
                event_rx: rx,
                presenter_pid,
            })
        }

        pub fn recv_event(&mut self) -> Option<gpu_share_proto::InputEvent> {
            self.event_rx.try_recv().ok()
        }

        pub async fn notify_surface(
            &mut self,
            surface: &super::SharedSurfaceInfo,
            handle: super::NativeHandle,
        ) -> Result<(), String> {
            let req = gpu_share_proto::SurfaceUpdate {
                surface: Some(gpu_share_proto::SharedSurfaceInfo {
                    width: surface.width,
                    height: surface.height,
                    format: surface.format,
                    memory_size: surface.memory_size,
                    memory_type_bits: surface.memory_type_bits,
                }),
                #[cfg(unix)]
                memory_handle: handle as u64,
                #[cfg(windows)]
                memory_handle: handle as u64,
            };
            self.client
                .notify_surface(req)
                .await
                .map_err(|e| format!("NotifySurface failed: {}", e))?;
            Ok(())
        }
    }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
fn main() {
    // Parse command line args
    let args: Vec<String> = std::env::args().collect();
    let mut port = "9710".to_string();
    let mut script_path = String::new();

    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--port" | "-p" => {
                if i + 1 < args.len() {
                    i += 1;
                    port = args[i].clone();
                }
            }
            "--script" => {
                if i + 1 < args.len() {
                    i += 1;
                    script_path = args[i].clone();
                }
            }
            _ => {}
        }
        i += 1;
    }

    if script_path.is_empty() {
        if let Ok(exe_path) = std::env::current_exe() {
            if let Some(dir) = exe_path.parent() {
                script_path = dir.join("scenes").join("1.ts").to_string_lossy().to_string();
            }
        }
        if script_path.is_empty() {
            script_path = "scenes/1.ts".to_string();
        }
    }

    // Set up graceful shutdown
    let running = Arc::new(AtomicBool::new(true));
    {
        let running = running.clone();
        ctrlc_simple(running);
    }

    // -----------------------------------------------------------------------
    // 1. Vulkan instance (headless, no surface extensions)
    // -----------------------------------------------------------------------
    eprintln!("[deno_renderer] Creating Vulkan instance (headless)...");

    let entry = unsafe { ash::Entry::load().expect("Failed to load Vulkan entry") };

    let app_name = c"deno_renderer";
    let engine_name = c"none";

    let app_info = vk::ApplicationInfo::default()
        .application_name(app_name)
        .application_version(vk::make_api_version(0, 1, 0, 0))
        .engine_name(engine_name)
        .engine_version(vk::make_api_version(0, 1, 0, 0))
        .api_version(vk::API_VERSION_1_3);

    let instance_extensions = [
        ash::khr::external_memory_capabilities::NAME.as_ptr(),
        ash::khr::external_semaphore_capabilities::NAME.as_ptr(),
        ash::khr::get_physical_device_properties2::NAME.as_ptr(),
        ash::ext::debug_utils::NAME.as_ptr(),
    ];
    let instance_extensions_cstr: &[&'static std::ffi::CStr] = &[
        ash::khr::external_memory_capabilities::NAME,
        ash::khr::external_semaphore_capabilities::NAME,
        ash::khr::get_physical_device_properties2::NAME,
        ash::ext::debug_utils::NAME,
    ];

    let validation_layer = c"VK_LAYER_KHRONOS_validation";
    let layers = [validation_layer.as_ptr()];

    let instance_ci = vk::InstanceCreateInfo::default()
        .application_info(&app_info)
        .enabled_extension_names(&instance_extensions)
        .enabled_layer_names(&layers);

    let instance = unsafe {
        entry
            .create_instance(&instance_ci, None)
            .expect("Failed to create VkInstance")
    };
    eprintln!("[deno_renderer] VkInstance created");

    // -----------------------------------------------------------------------
    // 2. Pick physical device
    // -----------------------------------------------------------------------
    let (phys_device, graphics_queue_family) = unsafe {
        let phys_devices = instance
            .enumerate_physical_devices()
            .expect("Failed to enumerate physical devices");
        if phys_devices.is_empty() {
            panic!("No Vulkan physical devices found");
        }

        let mut selected = None;
        for pd in &phys_devices {
            let queue_families = instance.get_physical_device_queue_family_properties(*pd);
            for (idx, qf) in queue_families.iter().enumerate() {
                if qf.queue_flags.contains(vk::QueueFlags::GRAPHICS) {
                    selected = Some((*pd, idx as u32));
                    break;
                }
            }
            if selected.is_some() {
                break;
            }
        }
        selected.expect("No physical device with graphics queue found")
    };

    unsafe {
        let props = instance.get_physical_device_properties(phys_device);
        let name = CStr::from_ptr(props.device_name.as_ptr());
        eprintln!("[deno_renderer] Using device: {}", name.to_string_lossy());
    }

    // -----------------------------------------------------------------------
    // 3. Create logical device (with external memory extensions)
    // -----------------------------------------------------------------------
    let queue_priority = [1.0f32];
    let queue_ci = vk::DeviceQueueCreateInfo::default()
        .queue_family_index(graphics_queue_family)
        .queue_priorities(&queue_priority);

    #[cfg(unix)]
    let device_extensions = [
        ash::khr::external_memory::NAME.as_ptr(),
        ash::khr::external_memory_fd::NAME.as_ptr(),
        ash::khr::external_semaphore::NAME.as_ptr(),
        ash::khr::external_semaphore_fd::NAME.as_ptr(),
        ash::khr::dedicated_allocation::NAME.as_ptr(),
        ash::khr::get_memory_requirements2::NAME.as_ptr(),
    ];
    #[cfg(unix)]
    let device_extensions_cstr: &[&'static std::ffi::CStr] = &[
        ash::khr::external_memory::NAME,
        ash::khr::external_memory_fd::NAME,
        ash::khr::external_semaphore::NAME,
        ash::khr::external_semaphore_fd::NAME,
        ash::khr::dedicated_allocation::NAME,
        ash::khr::get_memory_requirements2::NAME,
    ];

    #[cfg(windows)]
    let device_extensions = [
        ash::khr::external_memory::NAME.as_ptr(),
        ash::khr::external_memory_win32::NAME.as_ptr(),
        ash::khr::external_semaphore::NAME.as_ptr(),
        ash::khr::external_semaphore_win32::NAME.as_ptr(),
        ash::khr::dedicated_allocation::NAME.as_ptr(),
        ash::khr::get_memory_requirements2::NAME.as_ptr(),
    ];
    #[cfg(windows)]
    let device_extensions_cstr: &[&'static std::ffi::CStr] = &[
        ash::khr::external_memory::NAME,
        ash::khr::external_memory_win32::NAME,
        ash::khr::external_semaphore::NAME,
        ash::khr::external_semaphore_win32::NAME,
        ash::khr::dedicated_allocation::NAME,
        ash::khr::get_memory_requirements2::NAME,
    ];

    // Enable Vulkan 1.2 features needed by wgpu-hal
    let mut vulkan_12_features = vk::PhysicalDeviceVulkan12Features::default()
        .timeline_semaphore(true);

    let device_ci = vk::DeviceCreateInfo::default()
        .push_next(&mut vulkan_12_features)
        .queue_create_infos(std::slice::from_ref(&queue_ci))
        .enabled_extension_names(&device_extensions);

    let device = unsafe {
        instance
            .create_device(phys_device, &device_ci, None)
            .expect("Failed to create VkDevice")
    };
    eprintln!("[deno_renderer] VkDevice created");

    let graphics_queue = unsafe { device.get_device_queue(graphics_queue_family, 0) };

    // -----------------------------------------------------------------------
    // 4. Command pool
    // -----------------------------------------------------------------------
    let pool_ci = vk::CommandPoolCreateInfo::default()
        .flags(vk::CommandPoolCreateFlags::RESET_COMMAND_BUFFER)
        .queue_family_index(graphics_queue_family);

    let command_pool = unsafe {
        device
            .create_command_pool(&pool_ci, None)
            .expect("Failed to create command pool")
    };

    // -----------------------------------------------------------------------
    // 5. Shared exportable image
    // -----------------------------------------------------------------------
    let image_format = vk::Format::R8G8B8A8_UNORM;
    let initial_width: u32 = 640;
    let initial_height: u32 = 480;

    let shared_img = unsafe {
        create_shared_image(
            &instance,
            &device,
            phys_device,
            initial_width,
            initial_height,
            image_format,
        )
    };
    eprintln!("[deno_renderer] Shared image created");

    let render_img = unsafe {
        create_shared_image(&instance, &device, phys_device, initial_width, initial_height, image_format)
    };
    eprintln!("[deno_renderer] Render target created (double-buffer)");

    // Create timeline semaphore for frame synchronization
    #[cfg(unix)]
    let sem_handle_type = vk::ExternalSemaphoreHandleTypeFlags::OPAQUE_FD;
    #[cfg(windows)]
    let sem_handle_type = vk::ExternalSemaphoreHandleTypeFlags::OPAQUE_WIN32;

    let timeline_sem = unsafe {
        let mut sem_type_ci = vk::SemaphoreTypeCreateInfo::default()
            .semaphore_type(vk::SemaphoreType::TIMELINE)
            .initial_value(0);
        let mut export_ci = vk::ExportSemaphoreCreateInfo::default()
            .handle_types(sem_handle_type);
        let sem_ci = vk::SemaphoreCreateInfo::default()
            .push_next(&mut sem_type_ci)
            .push_next(&mut export_ci);
        device.create_semaphore(&sem_ci, None)
            .expect("Failed to create timeline semaphore")
    };

    // Export semaphore handle
    #[cfg(unix)]
    let sem_handle: NativeHandle = unsafe {
        let ext = ash::khr::external_semaphore_fd::Device::new(&instance, &device);
        let get_fd_info = vk::SemaphoreGetFdInfoKHR::default()
            .semaphore(timeline_sem)
            .handle_type(vk::ExternalSemaphoreHandleTypeFlags::OPAQUE_FD);
        ext.get_semaphore_fd(&get_fd_info)
            .expect("Failed to export semaphore fd") as NativeHandle
    };

    #[cfg(windows)]
    let sem_handle: NativeHandle = unsafe {
        let ext = ash::khr::external_semaphore_win32::Device::new(&instance, &device);
        let get_handle_info = vk::SemaphoreGetWin32HandleInfoKHR::default()
            .semaphore(timeline_sem)
            .handle_type(vk::ExternalSemaphoreHandleTypeFlags::OPAQUE_WIN32);
        ext.get_semaphore_win32_handle(&get_handle_info)
            .expect("Failed to export semaphore handle") as NativeHandle
    };

    eprintln!("[deno_renderer] Timeline semaphore created, handle={:?}", sem_handle);
    let mut frame_counter: u64 = 0;

    // -----------------------------------------------------------------------
    // 6. Build GpuState
    // -----------------------------------------------------------------------
    let gpu_state = Arc::new(Mutex::new(GpuState {
        instance: instance.clone(),
        device: device.clone(),
        phys_device,
        graphics_queue,
        graphics_queue_family,
        command_pool,
        render_img,
        shared_img,
        image_format,
        input_events: vec![],
        webgpu_active: false,
    }));

    // -----------------------------------------------------------------------
    // 7. Create wgpu-hal bridge (wraps ash objects for WebGPU)
    // -----------------------------------------------------------------------
    let bridge = unsafe {
        wgpu_hal_bridge::create_bridge(
            entry.clone(),
            instance.clone(),
            phys_device,
            device.clone(),
            graphics_queue_family,
            0, // queue_index
            instance_extensions_cstr,
            device_extensions_cstr,
        )
    }
    .expect("Failed to create wgpu-hal bridge");

    // Import the render image as a wgpu-core texture (scene renders here)
    let initial_texture_id = {
        let gpu = gpu_state.lock().unwrap();
        unsafe {
            wgpu_hal_bridge::import_texture(
                &bridge.global,
                bridge.device_id,
                gpu.render_img.image,    // Scene renders to render_img
                gpu.render_img.width,
                gpu.render_img.height,
                wgpu_types::TextureFormat::Rgba8Unorm,
            )
        }
        .expect("Failed to import render texture")
    };

    // Import the shared image as a second texture (presenter reads here)
    let initial_shared_texture_id = {
        let gpu = gpu_state.lock().unwrap();
        unsafe {
            wgpu_hal_bridge::import_texture(
                &bridge.global,
                bridge.device_id,
                gpu.shared_img.image,
                gpu.shared_img.width,
                gpu.shared_img.height,
                wgpu_types::TextureFormat::Rgba8Unorm,
            )
        }
        .expect("Failed to import shared texture")
    };

    // Staging buffer for prepare_for_present (reused across frames and resizes)
    let staging_buffer_id = wgpu_hal_bridge::create_staging_buffer(
        &bridge.global,
        bridge.device_id,
    )
    .expect("Failed to create staging buffer");

    // Track current texture IDs (change on resize)
    let mut current_render_texture_id = initial_texture_id;
    let mut current_shared_texture_id = initial_shared_texture_id;

    // -----------------------------------------------------------------------
    // 8. Connect to presenter via gRPC
    // -----------------------------------------------------------------------
    eprintln!(
        "[deno_renderer] Connecting to presenter gRPC on {}...",
        port
    );

    // -----------------------------------------------------------------------
    // 9. Deno runtime + render loop (JsRuntime stays alive through loop)
    // -----------------------------------------------------------------------
    {
        let gpu_clone = gpu_state.clone();

        deno_core::extension!(
            scene_ext,
            ops = [
                op_gpu_poll_events,
                op_gpu_set_webgpu_active,
                op_log
            ]
        );

        let tokio_rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("Failed to create tokio runtime");

        tokio_rt.block_on(async {
            // Connect to presenter gRPC server
            let surface_info = {
                let gpu = gpu_state.lock().unwrap();
                SharedSurfaceInfo {
                    width: gpu.shared_img.width,
                    height: gpu.shared_img.height,
                    format: image_format.as_raw() as u32,
                    memory_size: gpu.shared_img.memory_size,
                    memory_type_bits: gpu.shared_img.memory_type_bits,
                }
            };
            let connect_handle = {
                let gpu = gpu_state.lock().unwrap();
                gpu.shared_img.handle
            };
            let mut transport = transport::GrpcTransport::connect(
                &port,
                std::process::id(),
                &surface_info,
                connect_handle,
                sem_handle,
            )
            .await
            .unwrap_or_else(|e| panic!("Failed to connect: {}", e));
            eprintln!("[deno_renderer] Surface shared via gRPC.");

            let mut runtime = JsRuntime::new(RuntimeOptions {
                extensions: vec![
                    scene_ext::init(),
                    deno_webgpu::deno_webgpu::init(),
                ],
                ..Default::default()
            });

            // Old custom ops state
            runtime.op_state().borrow_mut().put(gpu_clone);

            // WebGPU bridge: inject pre-created wgpu-core objects into OpState
            {
                let op_state_rc = runtime.op_state();
                let mut op_state = op_state_rc.borrow_mut();
                // The Instance (Arc<Global>) must be in OpState for deno_webgpu
                op_state.put(bridge.global.clone() as deno_webgpu::Instance);
                op_state.put(deno_webgpu::InjectedAdapterId(bridge.adapter_id));
                op_state.put(deno_webgpu::InjectedDeviceIds {
                    device_id: bridge.device_id,
                    queue_id: bridge.queue_id,
                });
                op_state.put(deno_webgpu::InjectedTexture {
                    texture_id: initial_texture_id,
                    width: initial_width,
                    height: initial_height,
                    format: deno_webgpu::texture::GPUTextureFormat::Rgba8unorm,
                    usage: (wgpu_types::TextureUsages::RENDER_ATTACHMENT
                        | wgpu_types::TextureUsages::COPY_SRC
                        | wgpu_types::TextureUsages::COPY_DST
                        | wgpu_types::TextureUsages::TEXTURE_BINDING)
                        .bits(),
                });
            }

            // Load V8 polyfills (TextEncoder/TextDecoder) then protobuf bundle
            {
                let exe_dir = std::env::current_exe()
                    .ok()
                    .and_then(|p| p.parent().map(|d| d.to_path_buf()));
                let resolve = |name: &str| -> String {
                    exe_dir
                        .as_ref()
                        .map(|d| d.join(name).to_string_lossy().to_string())
                        .unwrap_or_else(|| name.to_string())
                };

                // Polyfill must run before proto_bundle.js (protobuf-es needs TextEncoder)
                let polyfill_path = resolve("v8_polyfill.js");
                match std::fs::read_to_string(&polyfill_path) {
                    Ok(code) => {
                        if let Err(e) = runtime.execute_script("<v8_polyfill>", code) {
                            eprintln!("[deno_renderer] Failed to load v8 polyfill: {}", e);
                        } else {
                            eprintln!("[deno_renderer] Loaded v8_polyfill.js");
                        }
                    }
                    Err(e) => {
                        eprintln!("[deno_renderer] Warning: could not load '{}': {}", polyfill_path, e);
                    }
                }

                let proto_bundle_path = resolve("proto_bundle.js");
                match std::fs::read_to_string(&proto_bundle_path) {
                    Ok(code) => {
                        if let Err(e) = runtime.execute_script("<proto_bundle>", code) {
                            eprintln!("[deno_renderer] Failed to load proto bundle: {}", e);
                        } else {
                            eprintln!("[deno_renderer] Loaded proto_bundle.js");
                        }
                    }
                    Err(e) => {
                        eprintln!(
                            "[deno_renderer] Warning: could not load '{}': {} (events will not be decoded in TS)",
                            proto_bundle_path, e
                        );
                    }
                }

                // WebGPU shim: sets up navigator.gpu and GPUBufferUsage etc.
                let webgpu_shim_path = resolve("webgpu_shim.js");
                match std::fs::read_to_string(&webgpu_shim_path) {
                    Ok(code) => {
                        if let Err(e) = runtime.execute_script("<webgpu_shim>", code) {
                            eprintln!("[deno_renderer] Failed to load webgpu shim: {}", e);
                        } else {
                            eprintln!("[deno_renderer] Loaded webgpu_shim.js");
                        }
                    }
                    Err(e) => {
                        eprintln!("[deno_renderer] Warning: could not load '{}': {}", webgpu_shim_path, e);
                    }
                }
            }

            // Load script — from URL if it starts with http(s)://, otherwise from file
            let script_result = if script_path.starts_with("http://")
                || script_path.starts_with("https://")
            {
                eprintln!("[deno_renderer] Fetching script: {}", script_path);
                match reqwest::get(&script_path).await {
                    Ok(resp) => {
                        if resp.status().is_success() {
                            resp.text().await.map_err(|e| format!("{}", e))
                        } else {
                            Err(format!("HTTP {}", resp.status()))
                        }
                    }
                    Err(e) => Err(format!("{}", e)),
                }
            } else {
                std::fs::read_to_string(&script_path).map_err(|e| format!("{}", e))
            };

            match script_result {
                Ok(code) => {
                    eprintln!("[deno_renderer] Running script: {}", script_path);
                    if let Err(e) = runtime.execute_script("<scene>", code) {
                        eprintln!("[deno_renderer] Script error: {}", e);
                    }
                    if let Err(e) = runtime.run_event_loop(Default::default()).await {
                        eprintln!("[deno_renderer] Event loop error: {}", e);
                    }
                }
                Err(e) => {
                    eprintln!(
                        "[deno_renderer] Error loading script '{}': {}",
                        script_path, e
                    );
                }
            }

            // ---------------------------------------------------------------
            // 9. Render loop — inside tokio block, JsRuntime alive
            // ---------------------------------------------------------------
            // Frame watchdog: terminate V8 if __frame runs longer than 1 second
            let isolate_handle = runtime.v8_isolate().thread_safe_handle();
            let frame_deadline = Arc::new(std::sync::atomic::AtomicU64::new(0));
            {
                let deadline = frame_deadline.clone();
                let handle = isolate_handle.clone();
                std::thread::spawn(move || {
                    loop {
                        std::thread::sleep(Duration::from_millis(10));
                        let dl = deadline.load(Ordering::Relaxed);
                        if dl > 0 {
                            let now = std::time::SystemTime::now()
                                .duration_since(std::time::UNIX_EPOCH)
                                .unwrap()
                                .as_millis() as u64;
                            if now > dl {
                                eprintln!("[deno_renderer] WARNING: __frame timed out (>1s), terminating");
                                handle.terminate_execution();
                                deadline.store(0, Ordering::Relaxed);
                            }
                        }
                    }
                });
            }
            const FRAME_TIMEOUT_MS: u64 = 1000;

            eprintln!("[deno_renderer] Entering render loop (Ctrl+C to exit)...");

            let start_time = std::time::Instant::now();
            let mut tab_paused = false;
            let mut pending_resize: Option<(u32, u32)> = None;
            let mut resize_deadline: Option<std::time::Instant> = None;
            const RESIZE_DEBOUNCE_MS: u64 = 150;

            while running.load(Ordering::Relaxed) {
                // Poll for input events from gRPC stream (non-blocking channel drain)
                while let Some(ev) = transport.recv_event() {
                    use gpu_share_proto::input_event::Event;
                    match &ev.event {
                        // Check for resize (needs Vulkan handling in Rust)
                        Some(Event::Resize(r)) => {
                            pending_resize = Some((r.width, r.height));
                            resize_deadline = Some(std::time::Instant::now() + Duration::from_millis(RESIZE_DEBOUNCE_MS));
                        }
                        Some(Event::TabPause(_)) => {
                            tab_paused = true;
                            eprintln!("[deno_renderer] Tab paused");
                        }
                        Some(Event::TabResume(_)) => {
                            tab_paused = false;
                            eprintln!("[deno_renderer] Tab resumed");
                        }
                        _ => {}
                    }

                    // Encode raw protobuf bytes for TypeScript consumption
                    let mut gpu = gpu_state.lock().unwrap();
                    gpu.input_events.push(ev.encode_to_vec());
                }

                // Handle resize (recreate shared image)
                let should_resize = pending_resize.is_some()
                    && resize_deadline.map_or(false, |d| std::time::Instant::now() >= d);
                if should_resize {
                    let (new_w, new_h) = pending_resize.take().unwrap();
                    resize_deadline = None;
                    let mut gpu = gpu_state.lock().unwrap();
                    if new_w > 0
                        && new_h > 0
                        && (new_w != gpu.shared_img.width || new_h != gpu.shared_img.height)
                    {
                        unsafe {
                            device.device_wait_idle().expect("device_wait_idle failed");

                            destroy_shared_image(&device, &mut gpu.render_img);
                            destroy_shared_image(&device, &mut gpu.shared_img);
                            gpu.render_img = create_shared_image(
                                &instance,
                                &device,
                                phys_device,
                                new_w,
                                new_h,
                                image_format,
                            );
                            gpu.shared_img = create_shared_image(
                                &instance,
                                &device,
                                phys_device,
                                new_w,
                                new_h,
                                image_format,
                            );
                        }

                        // Re-import render texture for WebGPU (scene renders here)
                        let new_render_tid = unsafe {
                            wgpu_hal_bridge::import_texture(
                                &bridge.global,
                                bridge.device_id,
                                gpu.render_img.image,
                                new_w,
                                new_h,
                                wgpu_types::TextureFormat::Rgba8Unorm,
                            )
                        };
                        // Re-import shared texture (presenter reads here)
                        let new_shared_tid = unsafe {
                            wgpu_hal_bridge::import_texture(
                                &bridge.global,
                                bridge.device_id,
                                gpu.shared_img.image,
                                new_w,
                                new_h,
                                wgpu_types::TextureFormat::Rgba8Unorm,
                            )
                        };
                        match (new_render_tid, new_shared_tid) {
                            (Ok(rtid), Ok(stid)) => {
                                current_render_texture_id = rtid;
                                current_shared_texture_id = stid;
                                let op_state_rc = runtime.op_state();
                                let mut op_state = op_state_rc.borrow_mut();
                                op_state.put(deno_webgpu::InjectedTexture {
                                    texture_id: rtid,  // Scene gets the render texture
                                    width: new_w,
                                    height: new_h,
                                    format: deno_webgpu::texture::GPUTextureFormat::Rgba8unorm,
                                    usage: (wgpu_types::TextureUsages::RENDER_ATTACHMENT
                                        | wgpu_types::TextureUsages::COPY_SRC
                                        | wgpu_types::TextureUsages::COPY_DST
                                        | wgpu_types::TextureUsages::TEXTURE_BINDING)
                                        .bits(),
                                });
                            }
                            (Err(e), _) | (_, Err(e)) => {
                                eprintln!("[deno_renderer] Failed to re-import texture: {}", e);
                            }
                        }

                        let si = SharedSurfaceInfo {
                            width: gpu.shared_img.width,
                            height: gpu.shared_img.height,
                            format: image_format.as_raw() as u32,
                            memory_size: gpu.shared_img.memory_size,
                            memory_type_bits: gpu.shared_img.memory_type_bits,
                        };
                        let _ = transport.notify_surface(&si, gpu.shared_img.handle).await;
                        eprintln!("[deno_renderer] Resized to {}x{}", new_w, new_h);
                    }
                }

                // Call JS frame callback (with watchdog timeout)
                let elapsed = start_time.elapsed().as_secs_f32();
                let frame_code = format!("if(globalThis.__frame)globalThis.__frame({})", elapsed);
                {
                    let now_ms = std::time::SystemTime::now()
                        .duration_since(std::time::UNIX_EPOCH)
                        .unwrap()
                        .as_millis() as u64;
                    frame_deadline.store(now_ms + FRAME_TIMEOUT_MS, Ordering::Relaxed);
                }
                if let Err(e) = runtime.execute_script("<frame>", frame_code) {
                    static LOGGED: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);
                    if !LOGGED.swap(true, Ordering::Relaxed) {
                        eprintln!("[deno_renderer] Frame callback error: {}", e);
                    }
                }
                frame_deadline.store(0, Ordering::Relaxed);

                // Copy render target -> shared image, then transition for presenter
                {
                    let gpu = gpu_state.lock().unwrap();
                    let w = gpu.render_img.width;
                    let h = gpu.render_img.height;
                    drop(gpu);
                    if let Err(e) = wgpu_hal_bridge::copy_and_present(
                        &bridge.global,
                        bridge.device_id,
                        bridge.queue_id,
                        current_render_texture_id,
                        current_shared_texture_id,
                        w,
                        h,
                        staging_buffer_id,
                    ) {
                        static LOGGED_ERR: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);
                        if !LOGGED_ERR.swap(true, Ordering::Relaxed) {
                            eprintln!("[deno_renderer] copy_and_present error: {}", e);
                        }
                    }
                }

                // Signal timeline semaphore for presenter sync
                frame_counter += 1;
                unsafe {
                    let signal_info = vk::SemaphoreSignalInfo::default()
                        .semaphore(timeline_sem)
                        .value(frame_counter);
                    device.signal_semaphore(&signal_info)
                        .expect("Failed to signal timeline semaphore");
                }

                // Must use tokio::time::sleep (not std::thread::sleep) so the
                // single-threaded tokio runtime can poll the StreamInput task.
                let sleep_ms = if tab_paused { 500 } else { 16 }; // ~2fps when paused, ~60fps active
                tokio::time::sleep(Duration::from_millis(sleep_ms)).await;
            }

        });
    }

    eprintln!("\n[deno_renderer] Shutting down...");

    // -----------------------------------------------------------------------
    // 11. Cleanup
    // -----------------------------------------------------------------------
    unsafe {
        device.device_wait_idle().expect("device_wait_idle failed");
    }

    // transport is dropped here (gRPC channel + streams close automatically)

    {
        let mut gpu = gpu_state.lock().unwrap();
        unsafe {
            destroy_shared_image(&device, &mut gpu.render_img);
            destroy_shared_image(&device, &mut gpu.shared_img);
            device.destroy_semaphore(timeline_sem, None);
            device.destroy_command_pool(command_pool, None);
            device.destroy_device(None);
            instance.destroy_instance(None);
        }
    }

    eprintln!("[deno_renderer] Cleanup complete");
}

// ---------------------------------------------------------------------------
// Simple ctrlc handler using signal
// ---------------------------------------------------------------------------
#[cfg(unix)]
fn ctrlc_simple(running: Arc<AtomicBool>) {
    unsafe {
        static mut RUNNING: Option<*const AtomicBool> = None;
        RUNNING = Some(Arc::into_raw(running));

        extern "C" fn handler(_: libc::c_int) {
            unsafe {
                if let Some(ptr) = RUNNING {
                    (*ptr).store(false, Ordering::Relaxed);
                }
            }
        }

        let mut sa: libc::sigaction = std::mem::zeroed();
        sa.sa_sigaction = handler as *const () as usize;
        libc::sigemptyset(&mut sa.sa_mask);
        sa.sa_flags = 0;
        libc::sigaction(libc::SIGINT, &sa, std::ptr::null_mut());
        libc::sigaction(libc::SIGTERM, &sa, std::ptr::null_mut());
    }
}

#[cfg(windows)]
fn ctrlc_simple(running: Arc<AtomicBool>) {
    unsafe {
        use windows_sys::Win32::System::Console::SetConsoleCtrlHandler;
        static mut RUNNING: Option<*const AtomicBool> = None;
        RUNNING = Some(Arc::into_raw(running));

        unsafe extern "system" fn handler(_: u32) -> i32 {
            if let Some(ptr) = RUNNING {
                (*ptr).store(false, Ordering::Relaxed);
            }
            1
        }

        SetConsoleCtrlHandler(Some(handler), 1);
    }
}
